name: Deploy to InfinityFree

on:
  push:
    branches:
      - main   # or master branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: ${{ secrets.if0_39984448 }}
          password: ${{ secrets.Mikaela2425 }}
          server-dir: /htdocs/
